Old/hacker-news-clone/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#index'

  resources :posts do
    resources :comments
  end

end

Old/hacker-news-clone/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :text, presence: true, length: { maximum: 50 }
  validates :post_id, presence: true
  validates :user_id, presence: true
end

Old/hacker-news-clone/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

Old/hacker-news-clone/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Old/hacker-news-clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Old/hacker-news-clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, except: [:create]
  before_action :require_same_user, only: [:destroy, :edit, :update]

  def create
    # debugger
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.js
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:success] = "Comment was successfully updated"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def require_same_user
    if @comment.user != current_user
      flash[:danger] = "You can only edit or delete your own comments"
      redirect_to root_path
    end
  end
end

Old/hacker-news-clone/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to posts_path
    end
  end
end

Old/hacker-news-clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:success] = "Post successfully created"
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post was successfully updated"
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy

    if request.xhr?
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :description)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_same_user
    if current_user != @post.user
      flash[:danger] = "You can only edit or deleted your own post"
      redirect_to root_path
    end
  end
end

Old/hacker-news-clone/app/helpers/application_helper.rb
module ApplicationHelper
end

Old/hacker-news-clone/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="row">
        <div class="col-xs-8 ">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h2 class="panel-title">
                #{sentence}
              </h2>

              <div class="panel-body">
                <ul>
                  #{messages}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    HTML

    html.html_safe
  end
end

Old/hacker-news-clone/app/views/comments/_comment.html.erb
<div class="well" id="<%= comment.id %>">
  <h5><%= comment.user.email %></h5>
  <p><%= comment.text %></p>

  <% if user_signed_in? && comment.user == current_user %>
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %> |
    <%= link_to "Delete", [comment.post, comment], remote: true, method: :delete %>
  <% end %>
</div>

Old/hacker-news-clone/app/views/comments/_form.html.erb
<%= render 'shared/errors', obj: @comment %>

<% # only use ajax if this is a new comment %>
<% useAjax = {} %>
<% if @comment.new_record? %>
  <% useAjax = { remote: true } %>
<% end %>

<%= form_for [@post, @comment], useAjax do |f| %>
  <div class="form-group">
    <label>Comment Text</label>
    <%= f.text_area :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-default btn-sm" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

Old/hacker-news-clone/app/views/comments/create.js.erb
'use strict';

$('#comments').append('<%= j render @comment %>').fadeIn(1000);
$('#comment_text').val('')

Old/hacker-news-clone/app/views/comments/destroy.js.erb
$('.well#<%= @comment.id %>').slideUp();

Old/hacker-news-clone/app/views/comments/edit.html.erb
<h1 class="page-header">Edit Comment</h1>

<%= render 'form' %>