Old/vehicle-tracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :cars

end

Old/vehicle-tracker/app/models/car.rb
class Car < ActiveRecord::Base
end

Old/vehicle-tracker/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Old/vehicle-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Old/vehicle-tracker/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
  end

  def new
    @car = Car.create
  end
end

Old/vehicle-tracker/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_path
    end
  end

  def dashboard
  end
end

Old/vehicle-tracker/app/helpers/application_helper.rb
module ApplicationHelper
  def isActive(controller, action = nil)
    if action == nil
      if params[:controller] == controller
        'active'
      end
    else
      if params[:controller] == controller && params[:action] == action
        'active'
      end
    end
  end
end

Old/vehicle-tracker/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="row">
        <div class="col-xs-8 ">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h2 class="panel-title">
                #{sentence}
              </h2>

              <div class="panel-body">
                <ul>
                  #{messages}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    HTML

    html.html_safe
  end
end

Old/vehicle-tracker/app/views/cars/_header.html.erb
<h1 class="page-header">Vehicles</h1>

<ul class="nav nav-tabs" style="margin-bottom: 25px">
  <li class="<%= isActive 'cars', 'index' %>">
    <%= link_to "All Vehicles", cars_path %>
  </li>
  <li class="<%= isActive 'cars', 'new' %>">
    <%= link_to "Add Vehicle", new_car_path %>
  </li>
</ul>

Old/vehicle-tracker/app/views/cars/index.html.erb
<%= render 'header' %>

Old/vehicle-tracker/app/views/cars/new.html.erb
<%= render 'header' %>

<%= form_for @car do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :year %>
        <%= f.text_field :year, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :make %>
        <%= f.text_field :make, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :model %>
        <%= f.text_field :model, class: "form-control" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :color %>
        <%= f.text_field :make, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :total_cost %>
        <%= f.text_field :total_cost, class: 'form-control' %>
      </div>
    </div>
  </div>
<% end %>

Old/vehicle-tracker/app/views/pages/dashboard.html.erb
<h1 class="page-header">Dashboard</h1>
<p>This is a test paragraph</p>

Old/vehicle-tracker/app/views/pages/index.html.erb
<h1 class="page-header">Home</h1>

<p>blah blah</p>